name: 'rabbitmqdemo'
services:
    bookstore-rabbitmq:
      image: rabbitmq:3.12.11-management
      container_name: my-rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"
        - "15672:15672"
      healthcheck:
        test: rabbitmq-diagnostics check_port_connectivity
        interval: 30s
        timeout: 30s
        retries: 10
      deploy:
        resources:
          limits:
            memory: 500m